<form id="loginform" method="post" class="form" action="<?php echo $this->url(array('module'=>'user',
																					'controller'=>'index',
																					'action'=>'login'))?>">
<h1>CMS</h1>
<ul>
	<li>
		<label>Username:</label>
		<input type="text" value="" />
	</li>
	<li>
		<label>Password:</label>
		<input type="password" value="" />
	</li>
	<li>
		<input type="submit" value="Submit" /> 
	</li>
</ul>
</form>